export const PERMISSIONS = {
  VIEW_DASHBOARD: 'view_dashboard',
  MANAGE_USERS: 'manage_users',
  MANAGE_DEPOSITS: 'manage_deposits',
  MANAGE_TRANSACTIONS: 'manage_transactions',
  MANAGE_GAMES: 'manage_games',
  MANAGE_SETTINGS: 'manage_settings',
  VIEW_AUDIT: 'view_audit',
  MANAGE_ADMINS: 'manage_admins'
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_DEPOSITS,
    PERMISSIONS.MANAGE_TRANSACTIONS,
    PERMISSIONS.MANAGE_GAMES,
    PERMISSIONS.VIEW_AUDIT
  ],
  SUPPORT: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.MANAGE_USERS, PERMISSIONS.VIEW_AUDIT],
  FINANCE: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.MANAGE_DEPOSITS, PERMISSIONS.MANAGE_TRANSACTIONS]
};
